import Foundation

/// Safe resolver for CodexBarCore's SwiftPM resource bundle.
///
/// The autogenerated `Bundle.module` accessor traps at launch when the packaged
/// app does not place `CodexBar_CodexBarCore.bundle` at the locations it probes
/// (the app root and the compile-time build directory). The packaged app ships
/// the bundle in `Contents/Resources`, so resolve through the main bundle first
/// and fall back to `Bundle.module` only outside an app context (SwiftPM dev
/// builds, the CLI, and tests), mirroring `resolveLocalizationResourceBundle`
/// and `ProviderBrandIcon.resourceBundle`.
public enum CodexBarCoreResources {
    public static let bundle: Bundle = resolve(mainBundle: .main)

    static func resolve(mainBundle: Bundle) -> Bundle {
        guard mainBundle.bundleURL.pathExtension == "app" else {
            return .module
        }
        let name = "CodexBar_CodexBarCore"
        if let url = mainBundle.url(forResource: name, withExtension: "bundle"),
           let bundle = Bundle(url: url)
        {
            return bundle
        }
        if let resourceURL = mainBundle.resourceURL,
           let bundle = Bundle(url: resourceURL.appendingPathComponent("\(name).bundle"))
        {
            return bundle
        }
        if let bundle = Bundle(url: mainBundle.bundleURL.appendingPathComponent("\(name).bundle")) {
            return bundle
        }
        return .module
    }
}
